apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develeap-test-app
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/Pikman/develeap-test-task.git'
    targetRevision: HEAD
    path: kubernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
